# Generated by Django 2.2.8 on 2020-01-13 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('preproject', '0017_auto_20200113_0929'),
    ]

    operations = [
        migrations.CreateModel(
            name='Handover',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remark', models.TextField(blank=True, max_length=1000, null=True)),
                ('problem_category', models.CharField(choices=[('e-sc', 'External - Scope Change'), ('e-rn', 'External - Renewal Process'), ('e-po', 'External - Conduct PSA After PO'), ('e-pr', 'External - Custom Product'), ('i-pc', 'Internal - PSA Form'), ('i-de', 'Internal - Delay to HO')], max_length=4)),
                ('oppty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='preproject.Preproject')),
            ],
        ),
        migrations.CreateModel(
            name='Cleanproject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oppty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='preproject.Preproject')),
            ],
        ),
    ]
