# Generated by Django 2.2.8 on 2020-01-13 10:55

from django.db import migrations, models
import datetime 

class Migration(migrations.Migration):

    dependencies = [
        ('handover', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='handover',
            name='po_date',
            field=models.DateField(default=datetime.datetime.now()),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='handover',
            name='po_known_date',
            field=models.DateField(default=datetime.datetime.now()),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='handover',
            name='submit_doc_projectcharter_date',
            field=models.DateField(default=datetime.datetime.now()),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='handover',
            name='submit_presales_handover_date',
            field=models.DateField(default=datetime.datetime.now()),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='handover',
            name='problem_category',
            field=models.CharField(choices=[('n-pr', 'No Problem - Fulfilled'), ('e-sc', 'External - Scope Change'), ('e-rn', 'External - Renewal Process'), ('e-po', 'External - Conduct PSA After PO'), ('e-pr', 'External - Custom Product'), ('i-pc', 'Internal - PSA Form'), ('i-de', 'Internal - Delay to HO')], default='n-pr', max_length=4),
        ),
    ]
