# Generated by Django 2.2.8 on 2020-02-23 23:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('psatopca', '0022_auto_20200120_1149'),
        ('handover', '0002_auto_20200113_1055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='handover',
            name='oppty',
        ),
        migrations.AddField(
            model_name='handover',
            name='pca',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='psatopca.Pca'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='handover',
            name='problem_category',
            field=models.CharField(choices=[('n-pr', 'No Problem - Fulfilled'), ('e-sc', 'External - Scope Change'), ('e-rn', 'External - Renewal Process'), ('e-po', 'External - Conduct PSA After PO'), ('e-pr', 'External - Custom Product'), ('i-pc', 'Internal - PCA Form'), ('i-de', 'Internal - Delay to HO')], default='n-pr', max_length=4),
        ),
    ]
