# Generated by Django 3.0.4 on 2020-05-08 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handover', '0003_auto_20200223_2306'),
    ]

    operations = [
        migrations.AddField(
            model_name='handover',
            name='pmois_status',
            field=models.CharField(choices=[('1', 'Project Charter - Draft'), ('2', 'Project Charter - Waiting Approval Presales GM'), ('3', 'Project Charter - Waiting Approval Delivery GM'), ('4', 'Project Charter - Waiting Approval PM'), ('5', 'Presales Handover - Draft'), ('6', 'Presales Handover - Waiting Approval PM'), ('7', 'Presales Handover - Approved')], default='1', max_length=1),
        ),
    ]
