# Generated by Django 3.0.4 on 2020-08-14 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('handover', '0006_auto_20200814_0926'),
    ]

    operations = [
        migrations.RenameField(
            model_name='handover',
            old_name='problem_category',
            new_name='clean_project_category',
        ),
    ]
