# Generated by Django 3.0.4 on 2020-08-14 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('psatopca', '0029_auto_20200810_1046'),
        ('handover', '0007_auto_20200814_0931'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CR_Overbudget',
            new_name='Changerequest_overbudget',
        ),
    ]
