# Generated by Django 2.2.8 on 2020-01-13 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preproject', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oppty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oppty_id', models.CharField(max_length=16)),
                ('project_name', models.CharField(max_length=100)),
                ('customer', models.ManyToManyField(to='preproject.Customer')),
            ],
        ),
        migrations.RemoveField(
            model_name='pre_project',
            name='opportunity_id',
        ),
        migrations.RemoveField(
            model_name='pre_project',
            name='project_name',
        ),
        migrations.AlterField(
            model_name='pre_project',
            name='customer',
            field=models.ManyToManyField(to='preproject.Oppty'),
        ),
    ]
