# Generated by Django 2.2.8 on 2020-01-13 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preproject', '0003_auto_20200113_0158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pre_project',
            name='issues',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='pre_project',
            name='remark',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
