# Generated by Django 2.2.8 on 2020-01-13 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('preproject', '0004_auto_20200113_0222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pre_project',
            name='opportunity',
        ),
        migrations.AddField(
            model_name='pre_project',
            name='opportunity',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='preproject.Oppty'),
            preserve_default=False,
        ),
    ]
