# Generated by Django 2.2.8 on 2020-01-13 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preproject', '0005_auto_20200113_0447'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pre_project',
            name='key_strategic_account',
        ),
        migrations.AddField(
            model_name='customer',
            name='key_strategic_account',
            field=models.BooleanField(default=False),
        ),
    ]
