# Generated by Django 2.2.8 on 2020-01-13 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preproject', '0006_auto_20200113_0450'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='key_strategic_account',
        ),
        migrations.AddField(
            model_name='customer',
            name='customercriteria',
            field=models.CharField(choices=[('ksa', 'Key Strategic Account'), ('sa', 'Strategic Account'), ('em', 'Emerging Account')], default=1, max_length=3),
            preserve_default=False,
        ),
    ]
