# Generated by Django 2.2.8 on 2020-01-13 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preproject', '0009_auto_20200113_0502'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='customercriteria',
            new_name='customer_criteria',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='customersegment',
            new_name='customer_segment',
        ),
    ]
