# Generated by Django 2.2.8 on 2020-01-13 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preproject', '0011_auto_20200113_0613'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pre_project',
            name='taxsonomi',
        ),
    ]
