# Generated by Django 2.2.8 on 2020-01-13 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preproject', '0012_remove_pre_project_taxsonomi'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Taxsonomi',
            new_name='Product',
        ),
        migrations.AddField(
            model_name='pre_project',
            name='taxsonomi',
            field=models.ManyToManyField(to='preproject.Product'),
        ),
    ]
