# Generated by Django 2.2.8 on 2020-01-13 06:15

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False # **<<< HERE**

    dependencies = [
        ('preproject', '0013_auto_20200113_0615'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Taxsonomi',
        ),
        migrations.RemoveField(
            model_name='pre_project',
            name='taxsonomi',
        ),
    ]
