# Generated by Django 2.2.8 on 2020-01-13 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preproject', '0014_auto_20200113_0615'),
    ]

    operations = [
        migrations.AddField(
            model_name='pre_project',
            name='taxsonomi',
            field=models.ManyToManyField(to='preproject.Taxsonomi'),
        ),
    ]
