# Generated by Django 2.2.8 on 2020-01-13 06:42

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False # **<<< HERE**
    dependencies = [
        ('psatopca', '0011_pca'),
        ('preproject', '0015_pre_project_taxsonomi'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pre_project',
            new_name='Preproject',
        ),
    ]
