# Generated by Django 2.2.8 on 2020-01-13 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preproject', '0016_auto_20200113_0642'),
    ]

    operations = [
        migrations.RenameField(
            model_name='preproject',
            old_name='opportunity',
            new_name='oppty',
        ),
        migrations.DeleteModel(
            name='PSA_PCA',
        ),
    ]
