# Generated by Django 2.2.8 on 2020-01-13 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preproject', '0018_auto_20200113_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preproject',
            name='progress',
            field=models.CharField(choices=[('w', 'Close Won'), ('l', 'Close Lost'), ('p', 'Progress - Internal SA'), ('s', 'Progress - Submited'), ('c', 'Cancelled'), ('h', 'PSA Hold')], max_length=1),
        ),
    ]
