# Generated by Django 2.2.8 on 2020-01-13 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preproject', '0019_auto_20200113_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preproject',
            name='solution_criteria',
            field=models.CharField(choices=[('s', 'Standard'), ('m', 'Multiservice'), ('cm', 'Complex MRC > 150JT'), ('co', 'Complex OTC > 1M'), ('cn', 'Complex Non Product')], max_length=2),
        ),
    ]
