# Generated by Django 2.2.8 on 2020-01-20 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preproject', '0020_auto_20200113_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_criteria',
            field=models.CharField(choices=[('0', 'Key Strategic Account'), ('1', 'Emerging Account'), ('2', 'Strategic Account'), ('3', 'New Customer & Not EA'), ('4', 'Regular')], max_length=1),
        ),
        migrations.AlterField(
            model_name='preproject',
            name='solution_criteria',
            field=models.CharField(choices=[('s', 'Standard'), ('m', 'Multiservice'), ('cm', 'Complex MRC > 150JT'), ('co', 'Complex OTC > 5M'), ('cn', 'Complex Non Product'), ('cc', 'Complex Custom Product')], max_length=2),
        ),
    ]
