# Generated by Django 2.2.8 on 2020-01-20 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preproject', '0021_auto_20200120_1032'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lintasartaperson',
            options={'ordering': ['initial', 'name']},
        ),
    ]
