# Generated by Django 2.2.8 on 2020-01-20 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preproject', '0022_auto_20200120_1102'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['customer_name']},
        ),
        migrations.AlterModelOptions(
            name='oppty',
            options={'ordering': ['project_name']},
        ),
    ]
