# Generated by Django 2.2.8 on 2020-01-27 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preproject', '0023_auto_20200120_1106'),
    ]

    operations = [
        migrations.CreateModel(
            name='PSSperson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial', models.CharField(max_length=3)),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['initial', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Salesperson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial', models.CharField(max_length=3)),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['initial', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SAperson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial', models.CharField(max_length=3)),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['initial', 'name'],
            },
        ),
    ]
