# Generated by Django 2.2.8 on 2020-01-27 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('preproject', '0024_pssperson_salesperson_saperson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preproject',
            name='sales_lintasarta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='preproject.Salesperson'),
        ),
    ]
