# Generated by Django 2.2.8 on 2020-01-27 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preproject', '0025_auto_20200127_1402'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SAperson',
            new_name='Solutionarchitectperson',
        ),
    ]
