# Generated by Django 2.2.8 on 2020-01-27 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preproject', '0026_auto_20200127_1512'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Solutionarchitectperson',
            new_name='Saperson',
        ),
    ]
