# Generated by Django 2.2.8 on 2020-01-27 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preproject', '0028_auto_20200127_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preproject',
            name='pss_lintasarta',
            field=models.ManyToManyField(to='preproject.Pssperson'),
        ),
    ]
