# Generated by Django 2.2.8 on 2020-01-27 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preproject', '0029_auto_20200127_1539'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Lintasartaperson',
        ),
        migrations.AlterField(
            model_name='preproject',
            name='pss_lintasarta',
            field=models.ManyToManyField(to='preproject.Pssperson'),
        ),
    ]
