# Generated by Django 2.2.8 on 2020-02-23 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preproject', '0030_auto_20200127_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preproject',
            name='pss_lintasarta',
            field=models.ManyToManyField(to='preproject.Pssperson'),
        ),
    ]
