# Generated by Django 2.2.8 on 2020-03-09 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preproject', '0031_auto_20200223_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preproject',
            name='pss_lintasarta',
            field=models.ManyToManyField(to='preproject.Pssperson'),
        ),
    ]
