# Generated by Django 3.0.4 on 2020-03-29 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preproject', '0032_auto_20200309_0938'),
    ]

    operations = [
        migrations.AddField(
            model_name='saperson',
            name='subbag',
            field=models.CharField(blank=True, choices=[('1', 'SA 1'), ('2', 'SA 2')], max_length=1),
        ),
        migrations.AlterField(
            model_name='preproject',
            name='pss_lintasarta',
            field=models.ManyToManyField(to='preproject.Pssperson'),
        ),
    ]
