# Generated by Django 3.0.4 on 2020-03-29 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preproject', '0033_auto_20200329_0816'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='preproject',
            options={'ordering': ['project_name']},
        ),
        migrations.RemoveField(
            model_name='preproject',
            name='oppty',
        ),
        migrations.AddField(
            model_name='preproject',
            name='customer',
            field=models.ManyToManyField(to='preproject.Customer'),
        ),
        migrations.AddField(
            model_name='preproject',
            name='oppty_id',
            field=models.CharField(default='n/a', max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='preproject',
            name='project_name',
            field=models.CharField(default='nama proyek', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='preproject',
            name='pss_lintasarta',
            field=models.ManyToManyField(to='preproject.Pssperson'),
        ),
        migrations.DeleteModel(
            name='Oppty',
        ),
    ]
