# Generated by Django 3.0.4 on 2020-03-31 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preproject', '0034_auto_20200329_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preproject',
            name='pss_lintasarta',
            field=models.ManyToManyField(to='preproject.Pssperson'),
        ),
    ]
