# Generated by Django 3.0.4 on 2020-05-08 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preproject', '0034_auto_20200329_0933'),
    ]

    operations = [
        migrations.CreateModel(
            name='Othersperson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial', models.CharField(max_length=3)),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('flag', models.CharField(choices=[('1', 'SA 1'), ('2', 'SA 2'), ('3', 'PSS SM'), ('4', 'SA SM')], max_length=1)),
            ],
            options={
                'ordering': ['initial', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='preproject',
            name='pss_lintasarta',
            field=models.ManyToManyField(to='preproject.Pssperson'),
        ),
    ]
