# Generated by Django 3.0.4 on 2020-04-01 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preproject', '0035_auto_20200401_0652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preproject',
            name='pss_lintasarta',
            field=models.ManyToManyField(to='preproject.Pssperson'),
        ),
    ]
