# Generated by Django 3.0 on 2019-12-05 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psatopca', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='psapca',
            name='attendance',
            field=models.TextField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
