# Generated by Django 2.2.8 on 2019-12-17 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psatopca', '0002_psapca_attendance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='psapca',
            name='customer',
        ),
        migrations.AddField(
            model_name='psapca',
            name='sub_dept',
            field=models.CharField(choices=[('sa1', 'Rully Mustofa'), ('sa2', 'Rachmat Hidayat')], default=0, max_length=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='psapca',
            name='pca_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
