# Generated by Django 2.2.8 on 2019-12-17 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('preproject', '0001_initial'),
        ('psatopca', '0003_auto_20191217_0811'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oppty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oppty_id', models.CharField(max_length=16)),
                ('customer', models.ManyToManyField(to='preproject.Customer')),
            ],
        ),
        migrations.AddField(
            model_name='psapca',
            name='oppty',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='psatopca.Oppty'),
            preserve_default=False,
        ),
    ]
