# Generated by Django 2.2.8 on 2020-01-09 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('preproject', '0001_initial'),
        ('psatopca', '0004_auto_20191217_0815'),
    ]

    operations = [
        migrations.CreateModel(
            name='Psa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('psa_date', models.DateField()),
                ('product_category', models.CharField(choices=[('d', 'Datacomm'), ('i', 'ITS')], max_length=1)),
                ('project_name', models.CharField(max_length=100)),
                ('productornot', models.CharField(choices=[('p', 'Product'), ('n', 'Non Product')], max_length=1)),
                ('scale', models.CharField(choices=[('s', 'Small'), ('m', 'Medium'), ('l', 'Large')], max_length=1)),
                ('summary', models.TextField(max_length=1000)),
                ('status', models.CharField(choices=[('g', 'GO'), ('h', 'HOLD'), ('n', 'NOT GO')], max_length=1)),
                ('remark', models.TextField(max_length=1000)),
                ('attendance', models.TextField(max_length=1000)),
                ('sub_dept', models.CharField(choices=[('sa1', 'Rully Mustofa'), ('sa2', 'Rachmat Hidayat')], max_length=3)),
                ('table_updated', models.DateField(auto_now=True)),
                ('table_creation_timestamp', models.DateField(auto_now_add=True)),
                ('oppty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='psatopca.Oppty')),
                ('pss_lintasarta', models.ManyToManyField(related_name='_psa_pss_lintasarta_+', to='preproject.Lintasartaperson')),
                ('sales_lintasarta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='preproject.Lintasartaperson')),
            ],
        ),
        migrations.DeleteModel(
            name='Psapca',
        ),
    ]
