# Generated by Django 2.2.8 on 2020-01-13 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('psatopca', '0005_auto_20200109_1220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='psa',
            name='oppty',
        ),
        migrations.DeleteModel(
            name='Oppty',
        ),
    ]
