# Generated by Django 2.2.8 on 2020-01-13 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psatopca', '0007_psa_oppty'),
    ]

    operations = [
        migrations.RenameField(
            model_name='psa',
            old_name='status',
            new_name='status_psa',
        ),
        migrations.RemoveField(
            model_name='psa',
            name='product_category',
        ),
        migrations.RemoveField(
            model_name='psa',
            name='project_name',
        ),
        migrations.RemoveField(
            model_name='psa',
            name='pss_lintasarta',
        ),
        migrations.RemoveField(
            model_name='psa',
            name='sales_lintasarta',
        ),
        migrations.AlterField(
            model_name='psa',
            name='remark',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
