# Generated by Django 2.2.8 on 2020-01-13 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psatopca', '0008_auto_20200113_0222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='psa',
            name='attendance',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='psa',
            name='status_psa',
            field=models.CharField(choices=[('GO', 'GO'), ('HOLD', 'HOLD'), ('NOT GO', 'NOT GO')], max_length=6),
        ),
    ]
