# Generated by Django 2.2.8 on 2020-01-13 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psatopca', '0009_auto_20200113_0229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='psa',
            name='status_psa',
            field=models.CharField(choices=[('g', 'GO'), ('h', 'HOLD'), ('n', 'NOT GO')], max_length=1),
        ),
    ]
