# Generated by Django 2.2.8 on 2020-01-13 04:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('psatopca', '0010_auto_20200113_0257'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pca_date', models.DateField()),
                ('status_pca', models.CharField(choices=[('g', 'GO'), ('h', 'HOLD'), ('n', 'NOT GO')], max_length=1)),
                ('ebitda', models.IntegerField(blank=True, null=True)),
                ('irr', models.IntegerField(blank=True, null=True)),
                ('remark', models.TextField(blank=True, max_length=1000, null=True)),
                ('attendance', models.TextField(blank=True, max_length=1000, null=True)),
                ('table_updated', models.DateField(auto_now=True)),
                ('table_creation_timestamp', models.DateField(auto_now_add=True)),
                ('psa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='psatopca.Psa')),
            ],
        ),
    ]
