# Generated by Django 2.2.8 on 2020-01-13 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psatopca', '0011_pca'),
    ]

    operations = [
        migrations.AddField(
            model_name='pca',
            name='problem_category',
            field=models.CharField(choices=[('e-ra', 'External - Resource Assessment'), ('e-sc', 'External - Scope Change'), ('e-cb', 'External - Source Costbase'), ('e-vc', 'External - Very Complex'), ('i-so', 'Internal - Incorrect Solution'), ('i-bp', 'Internal - Incorrect Price')], default=1, max_length=4),
            preserve_default=False,
        ),
    ]
