# Generated by Django 2.2.8 on 2020-01-13 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psatopca', '0012_pca_problem_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pca',
            name='problem_category',
            field=models.CharField(choices=[('n-pr', 'No Problem - Fulfilled'), ('e-ra', 'External - Resource Assessment'), ('e-sc', 'External - Scope Change'), ('e-cb', 'External - Source Costbase'), ('e-vc', 'External - Very Complex'), ('i-so', 'Internal - Incorrect Solution'), ('i-bp', 'Internal - Incorrect Price')], default='n-pr', max_length=4),
        ),
    ]
