# Generated by Django 2.2.8 on 2020-01-13 15:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('psatopca', '0013_auto_20200113_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='psa',
            name='pss_ho_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
