# Generated by Django 2.2.8 on 2020-01-13 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('psatopca', '0015_auto_20200113_1544'),
    ]

    operations = [
        migrations.RenameField(
            model_name='psa',
            old_name='oppty',
            new_name='preproject',
        ),
    ]
