# Generated by Django 2.2.8 on 2020-01-13 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psatopca', '0016_auto_20200113_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='psa',
            name='sub_dept',
            field=models.CharField(choices=[('sa1', 'SA 1 Sub Dept'), ('sa2', 'SA 2 Sub Dept')], max_length=3),
        ),
    ]
