# Generated by Django 2.2.8 on 2020-01-20 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psatopca', '0017_auto_20200113_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pca',
            name='status_pca',
            field=models.CharField(choices=[('g', 'GO/APPROVED'), ('h', 'HOLD'), ('n', 'NOT GO')], max_length=1),
        ),
    ]
