# Generated by Django 2.2.8 on 2020-01-20 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psatopca', '0019_auto_20200120_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pca',
            name='ebitda',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pca',
            name='irr',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
            preserve_default=False,
        ),
    ]
