# Generated by Django 2.2.8 on 2020-01-20 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psatopca', '0021_auto_20200120_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pca',
            name='mrc',
            field=models.DecimalField(decimal_places=2, max_digits=30),
        ),
        migrations.AlterField(
            model_name='pca',
            name='otc',
            field=models.DecimalField(decimal_places=2, max_digits=30),
        ),
    ]
