# Generated by Django 2.2.8 on 2020-03-09 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psatopca', '0022_auto_20200120_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='psa',
            name='risk_category',
            field=models.CharField(choices=[('l', 'low Risk'), ('m', 'Medium Risk'), ('h', 'High Risk')], default='m', max_length=1),
            preserve_default=False,
        ),
    ]
