# Generated by Django 3.0.4 on 2020-03-28 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psatopca', '0023_psa_risk_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='psa',
            name='risk_category',
            field=models.CharField(choices=[('l', 'Low Risk'), ('m', 'Medium Risk'), ('h', 'High Risk'), ('n', 'N/A')], max_length=1),
        ),
    ]
