# Generated by Django 3.0.4 on 2020-03-31 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psatopca', '0024_auto_20200328_0940'),
    ]

    operations = [
        migrations.AddField(
            model_name='pca',
            name='flagcalc',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
