# Generated by Django 3.0.4 on 2020-04-01 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psatopca', '0025_pca_flagcalc'),
    ]

    operations = [
        migrations.AddField(
            model_name='pca',
            name='tcv',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=30),
            preserve_default=False,
        ),
    ]
