# Generated by Django 3.0.4 on 2020-05-08 02:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('psatopca', '0026_pca_tcv'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pssho',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('psa_doc', models.BooleanField(default=False, verbose_name='Project Selection Approval')),
                ('resource_assessment_doc', models.BooleanField(default=False, verbose_name='Resource Assessment')),
                ('risk_assessment_doc', models.BooleanField(default=False, verbose_name='Risk Assessment')),
                ('brs_doc', models.BooleanField(default=False, verbose_name='Business Requirement Specification (BRS)')),
                ('rks_doc', models.BooleanField(default=False, verbose_name='RKS Tender (if available)')),
            ],
        ),
        migrations.AddField(
            model_name='psa',
            name='flagsendemail',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='psa',
            name='pss_ho_detail',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='psatopca.Pssho'),
        ),
    ]
