# Generated by Django 3.0.4 on 2020-05-14 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psatopca', '0027_auto_20200508_0927'),
    ]

    operations = [
        migrations.AddField(
            model_name='pssho',
            name='remark',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='psa',
            name='flagsendemail',
            field=models.BooleanField(default=False),
        ),
    ]
